# Generated by Django 5.1.2 on 2024-10-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_debts_friendship_delete_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
