# Generated by Django 5.1.2 on 2024-10-28 14:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_date_completed_event_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friendship',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікує підтвердження'), ('accepted', 'Прийнято'), ('rejected', 'Відхилено')], default='pending', max_length=10),
        ),
    ]
